### ISSUE TITLE
scroll doesn't go to expected element in responsive design

### ISSUE THREAD

**Issue by pazams** [zengabor/zenscroll#1]
@zengabor thanks for this great module.
I think I've found a bug. 

**the flow:**
1. goto http://plnkr.co/edit/N9iGxvHYz6eAXLCHEhmc?p=preview
2. shrink the size of the window so the 3 divs will be stacked one below the other.
3. find the text input at bottom of the page, and type "foo2"
4. click "scroll" button.

**result:**
scrolling to top of the screen.

**expected result:**
scrolling to top of "foo2" div.

**Another issue in same demo link:**
With Firefox 41.0.2 you will need multiple clicks (around 9) to fully fire the scroll.

**Comment by zengabor** [comment]
Thank you very much @pazams for reporting it. Looks like this is because plnkr.co runs the code in an iframe and Zenscroll isn't prepared for that. Give me some time to fix it.

**Comment by pazams** [comment]
@zengabor thanks for your quick response.
When removing the responsive bootstrap elements, the scrolling works as expected - http://plnkr.co/edit/ijvrKf?p=preview
Furthermore, I ran these 2 demos from localhost with no iframes, and they demonstrated the  same behaviour as when ran through plnkr.co

**Comment by zengabor** [comment]
Thank you! I am going to check the compatibility with those responsive bootstrap elements then.

**Comment by pazams** [comment]
compare http://plnkr.co/edit/HF51VG?p=preview linked to the fork with the fix,
to http://plnkr.co/edit/N9iGxvHYz6eAXLCHEhmc?p=preview  with the original behavior.
The PR referenced above doesn't fix the premature scroll stop. I've opened a separate issue https://github.com/zengabor/zenscroll/issues/3

**Comment by zengabor** [comment]
Just released version 2.0.0 which fixes this issue. 
https://github.com/zengabor/zenscroll

Thanks for your help, @pazams
