### ISSUE TITLE
Can't adjust edgeOffset

### ISSUE THREAD

**Issue by eddts** [zengabor/zenscroll#11]
Thanks for the library, just what i needed, but...

`if (!edgeOffset || edgeOffset !== 0) {
    // When scrolling, this amount of distance is kept from the edges of the scrollContainer:
    edgeOffset = 9 //px
}`

... If edgeOffset is false (0, null, undefined), or it's not exactly 0...

That conditional can never fail, so it always set's the offset to 9px!

**Comment by zengabor** [comment]
Oops, that should be obviously `&&`

Sorry about that. Will release a fix soon.

**Comment by zengabor** [comment]
Hi @eddts, this is now fixed in 3.0.2

**Comment by eddts** [comment]
Brilliant, thanks again for library!
