### ISSUE TITLE
Don't scroll on empty hash

### ISSUE THREAD

**Issue by rhewitt22** [zengabor/zenscroll#13]
I have a nested navigation bar composed of links, which support keyboard navigation of the menu through the use of the tab key.  The top level items trigger submenus (`href="#"`) and are not intended to trigger scrolling (zenscroll automatically scrolls to the top of the page in this scenario).  

Is there any way to disable auto scrolling if the hash is empty beyond the hash itself?

**Comment by rhewitt22** [comment]
![may-13-2016 07-37-33](https://cloud.githubusercontent.com/assets/3673374/15246798/9aa10f40-18dd-11e6-9a3a-cd5d6f517cff.gif)

**Comment by zengabor** [comment]
I understand your proposal. It would be also easy to implement. The thing is, however, that `href="#"` is a valid local reference, pointing to the top of the page. Zenscroll is trying to do the right thing here as long as these links stay as they are.

Is there a way you can change those links? For example, to `href="javascript:void(0)"`. Another way is to use a non-existing id, like `href="#zen"` in which case Zenscroll won't be activated. If you wrote the menu handling JavaScript module yourself then you could probably do an `event.preventDefault()` when you handle the menu selection, making sure that nothing else handles it. And there can be other solutions, depending on the code.

Hope this helps. If not, feel free to write again.

Nice site, by the way.

**Comment by rhewitt22** [comment]
@zengabor I didn't realize that `href="#"` was a valid method for pointing to the top of the page; I'd always manually added an element with `id="top"`.  Learn something new every day!

I wrote the navigation module so I can just stick an `e.preventDefault()` call in there.

Thanks for the suggestions!
