### ISSUE TITLE
window.getComputedStyle(node)['scroll-behavior'] returns true in IE browsers

### ISSUE THREAD

**Issue by possibilities** [zengabor/zenscroll#15]
Possibly you should remove the and provide a configuration options for this? Happy to PR this if you're in favor.

**Comment by zengabor** [comment]
Thank you, I will look into this

**Comment by zengabor** [comment]
Can you help me reproduce this? Which IE versions did you try? How did you find the `true` value? 
I could not reproduce this in the following browsers: IE11, IE10, IE9 (and earlier browsers are excluded as they don't support `getComputedStyle()`)
