### ISSUE TITLE
Demo 7 scroll intoview does not work when the scroll would be upwards 

### ISSUE THREAD

**Issue by giorgio79** [zengabor/zenscroll#17]
Just tired playing with the tool at https://zengabor.github.io/zenscroll/ and option 7, scrolltoview does not work when the scrolling would need to happen upwards.

**Comment by zengabor** [comment]
That's indeed a bug. Thank you for reporting. I am going to fix it.

**Comment by zengabor** [comment]
Fixed in v3.2.1

Container elements now must have their `position` CSS attribute set to `relative`, `absolute` or `fixed`. This way positioning works perfectly.
