### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by davishmcclurg** [zengabor/zenscroll#18]
Have you looked into adding support for horizontal scrolling?

Thanks for working on this. It's a nice little library.

**Comment by zengabor** [comment]
This would be an easy extension but I think it is needed only rarely so I rather leave it out to keep the script small and simple. I may do it in a separate script file thou as soon as I need this functionality someday. 😊

**Comment by ostrgard** [comment]
@zengabor +1 for this, in case you're counting :)

**Comment by fagri** [comment]
@zengabor +1 for this. It would be useful for projects with lists like Asana, Zenhub. Open a list and scroll into view..
