### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Julianoe** [zengabor/zenscroll#21]
I don't know what i'm doing wrong but i can't seem to make it work.
The files are well included into my page's code and i reproduced the example 7 but still it does not work and my browser says "zenscroll is not defined".... what did i miss ?

side question : do you have some working example of smooth scroll in a scrollable div ?

**Comment by zengabor** [comment]
Hi Julien, can you show me your code? Make sure you follow the install instructions: http://zengabor.github.io/zenscroll/#gettingstarted

You can find some examples for scrolling a div here: http://zengabor.github.io/zenscroll/#7.scrollinsideascrollablediv

Gabor

**Comment by englishextra** [comment]
I had zenscroll 1.0.0 perhaps a year a go or so and still use it https://github.com/englishextra/englishextra.github.io/blob/master/libs/englishextra-ui/js/bundle.js

well today i downloaded with npm as module and it wont work on electron via require and then browserify

Just took the code 3.21 and deleted all the browserify wrapping functions just in a clear manner

it doesnt work

electron debugger says something bad about getBoundingRectangle blablabla
and in browser zenscroll is not defined

```
var crel = require("crel"),
zenscroll = require("zenscroll");

var h1 = document.getElementById("h1");
crel(h1, 'Page title');
```
I'm tired to reproduce again to send you the debugging text
```
bundle.min.js:9 Uncaught TypeError: zenscroll.to is not a function
```

and in regular browser http-server environment

```
Timestamp: 12.08.2016 23:55:15
Error: TypeError: zenscroll.to is not a function
Source File: http://127.0.0.1:8080/js/bundle.min.js
Line: 4
```

 * Zenscroll 3.2.1
Its Electron  "electronVersion": "1.3.2"
and browserify of today 13.1.0

Hey, What's the rush? Can't you test such things, the environment above is not specific.
Everyone now is trying to catch up with MODULES. Please advise on sort of a patch (which is bad), 
and be a star.
