### ISSUE TITLE
Setting 'overflow-x: hidden' breaks it

### ISSUE THREAD

**Issue by davidbwaters** [zengabor/zenscroll#26]
Hi, I was going crazy trying to figure out how I broke it, but it was setting `overflow-x` to hidden on the body element because I was experimenting with an off canvas nav that I didn't want to stretch the container. I tweaked the CSS and got it working without hiding the overflow, but it was unpleasant to debug. A workaround or mention in the docs would be awesome.  Thanks.

**Comment by zengabor** [comment]
Are you sure the issue was caused only by `overflow-x: hidden`?

I did a quick test by setting `overflow-x: hidden` on the [test page](https://zengabor.github.io/zenscroll/) and could not reproduce it. :/

**Comment by davidbwaters** [comment]
Yes, on the body element.  When I switch it on in the inspector it no longer works. I'll try to share something showing it.

**Comment by zengabor** [comment]
I would be interested in it because I could not reproduce it.

**Comment by davidbwaters** [comment]
Sorry for the delay, took a break from working on that project.  Here is a live demo: http://ppt2.limberlogic.com/demo/videos.html
Click 'Challenges' and it works.  Set `overflow-x` to `hidden` and it fails.  Tested on Chrome, Windows.

**Comment by zengabor** [comment]
Yes, on this site I can see the issue. Interesting.

Not sure why this happens but I found it how you can fix it: remove `overflow-x: hidden` from `html` (it's in your CSS definition). Boom.

**Comment by davidbwaters** [comment]
Yes, I figured that out as a workaround, just thought I'd share.  It was just one of those odd/unexpected things that was tricky to debug when everything looked correct.  At least the closed issue will be here for others who may run into it.  Thanks.

**Comment by zengabor** [comment]
Thank you for that!
