### ISSUE TITLE
Error if loaded from within `head`

### ISSUE THREAD

**Issue by zengabor** [zengabor/zenscroll#27]
If the script is put inside the `head` as opposed to the `body` it causes an error:

    Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

**Comment by chrisharrisonkiwi** [comment]
Oh no!
This is a bit of a deal-breaker unfortunately, any progress on this?

**Comment by zengabor** [comment]
Not implemented yet. Maybe I can implement it this week, we'll see.

**Comment by kevnk** [comment]
But putting it before the closing `</body>` tag works great still for me ;)

**Comment by zengabor** [comment]
Would you mind testing the 4.0 release candidate?

You can find it here: https://github.com/zengabor/zenscroll/tree/gh-pages

**Comment by zengabor** [comment]
Implemented in v4.0.0
