### ISSUE TITLE
scroll stops after first iteration, multiple calls needed to trigger continous loop.

### ISSUE THREAD

**Issue by pazams** [zengabor/zenscroll#3]
as mentioned also in https://github.com/zengabor/zenscroll/issues/1, this now seems to a separate issue, as fixing the element top calculation doesn't fix the premature scroll stop.

**the flow:**
1. goto http://plnkr.co/edit/N9iGxvHYz6eAXLCHEhmc?p=preview
2. shrink the size of the window so the 3 divs will be stacked one below the other.
3. find the text input at bottom of the page, and type "foo2"
4. click "scroll" button.

**result:**
scrolls stops after a few pixels. multiple button clicks needed to trigger smooth scroll.
verified on IE11, firefox 41, and chromium 45 (linux).

**expected result:**
full smooth scroll.

**quick analysis:**
I inserted some `console.log`'s, and it appears that after in the first iteration, the following condition isn't met:

``` javascript
if (p < 1 && (getViewHeight() + y) < (scrollContainer || docElem).scrollHeight)
```

conditioning only on `p` solves the issue

``` javascript
if (p < 1)
```

@zengabor, I'll wait for your remarks before attempting a PR, or wait for your fix.

**Comment by zengabor** [comment]
Just released version 2.0.0 which fixes this issue. 
https://github.com/zengabor/zenscroll

Thanks for your help, @pazams!
