### ISSUE TITLE
Scrolling broken in Chrome if enclosing DIV is set to "absolute"

### ISSUE THREAD

**Issue by Naudiz** [zengabor/zenscroll#30]
I'm experiencing problems using zenscroll in Chrome. It stops working if any of the DIV-containers enclosing the anchor points has a position set to "absolute" in CSS. I have enclosed a very simple example file.
[Scrolltest.zip](https://github.com/zengabor/zenscroll/files/688330/Scrolltest.zip)

It is a very simple file with nothing but a single link and an anchorpoint to jump to. If you delete or comment-out the "position:absolute" in the CSS file, it will scroll normally. Otherwise it will not jump at all.

Tested with Chrome v.55.
On Firefox and Internet Explorer this problem doesn't exist, they scroll just fine either way.

**Comment by zengabor** [comment]
Thanks for reporting it and the attached zip. This is a bug. It is also reproducible in Safari.

**Comment by zengabor** [comment]
Would you mind testing the 4.0 release candidate?

You can find it here: https://github.com/zengabor/zenscroll/tree/gh-pages

**Comment by Naudiz** [comment]
The RC seems to fix the problem with Chrome, it scrolls properly now. But for some reason it now seems to be broken in Firefox. FF now jumps instantly, without scroll effect.

**Comment by zengabor** [comment]
Thank you very much, I can reproduce it. Looking into it.

**Comment by zengabor** [comment]
Fixed for Firefox. It was an edge case but very useful. Thank you!

**Comment by zengabor** [comment]
Fixed in v4.0.0
