### ISSUE TITLE
clicks do not trigger hashchange anymore

### ISSUE THREAD

**Issue by MartinMuzatko** [zengabor/zenscroll#31]
Hello!

I have a problem that when listening to `hashchange`, the eventhandler isn't triggered anymore.
works: http://codepen.io/MartinMuzatko/pen/RKpBEx (without zenscroll)
doesn't work: http://codepen.io/MartinMuzatko/pen/zNZLOQ (with zenscroll)

You can test that by clicking the anchors and see what happens.
While the hash is changed, the eventhandler does not work anymore.

Any idea why?

**Comment by zengabor** [comment]
It's not implemented. Zenscroll needs to be updated to raise this event.

**Comment by MartinMuzatko** [comment]
Any other events to listen to after the hash has changed as a workaround?
Thank you for the fast response :)

**Comment by zengabor** [comment]
Unfortunately, I don't think there would be any other event you could listen to. Of course if you really need it, you can keep polling `window.location.hash` and detect when it changes (e.g., via `setInterval()`).

Well, thank you for reporting. :) I will implement it but not exactly sure when.

**Comment by zengabor** [comment]
Implementation is already in progress, will arrive in version 4.0 in a week or so. Sorry for the delay.

**Comment by zengabor** [comment]
Would you mind testing the 4.0 release candidate?

You can find it here: https://github.com/zengabor/zenscroll/tree/gh-pages

You have to set the edge offset to zero via `zenscroll.setup(null, 0)` as described under 1.3 here: https://zengabor.github.io/zenscroll/#1.3.limitedsupportforthehashchangeeventandthecsspseudo:target

**Comment by zengabor** [comment]
Fixed in v4.0.0

Limitation: edge offset must be set to zero, e.g., `zenscroll.setup(null, 0)`
