### ISSUE TITLE
Not scrolling on iOS with a fixed header. 

### ISSUE THREAD

**Issue by Xalladus** [zengabor/zenscroll#34]
I am having an issue with the scrolling not responding at all when I am using my iPhone (safari/chrome) to view the page. It works fine everywhere else. So there must be some little thing I am missing to have this work on mobile. 

This is the example codepen. 
https://codepen.io/Xalladus/pen/YZOJeX

Please help!

**Comment by zengabor** [comment]
Thanks for the accurate report, I can reproduce it. Will investigate and fix it

**Comment by Finesse** [comment]
The scroll works when the page is not in an iframe (e.g. in CodePen debug mode)

**Comment by zengabor** [comment]
Can't reproduce this anymore, possibly because Safari on iPhones now supports the smooth scrolling behavior, see https://caniuse.com/css-scroll-behavior
