### ISSUE TITLE
Does not work with images that have an anchor link

### ISSUE THREAD

**Issue by apod42** [zengabor/zenscroll#4]
Hello,

Apparently script does not work with images that have an anchor link. If I replace the image with the text "go back to top", the script works ok.

<a href="#back_to_top"><img id="my_image" src="http://www.example.com/top.png" alt="Back to top" /></a>

Demo here: https://jsfiddle.net/gydbjqua/

The anchor link containing text works, the one with the image does not work.

**Comment by apod42** [comment]
I see the code I entered is formated as html in the box above...

**Comment by zengabor** [comment]
Thanks for reporting it, @apod42. I can reproduce this bug. I am going to fix it.

**Comment by zengabor** [comment]
Fixed it yesterday. There will be a new version soon. I just need to test all functionality (including image links) in all browsers now. I can probably release it in 14 hours or so. Thanks again, @apod42

**Comment by apod42** [comment]
Thank you, waiting patiently for the new version :)

**Comment by zengabor** [comment]
Just released version 2.0.0 which fixes this issue. 
https://github.com/zengabor/zenscroll

Thanks, @apod42
