### ISSUE TITLE
Provide selector to exclude specific links

### ISSUE THREAD

**Issue by MartinMuzatko** [zengabor/zenscroll#41]
Hi there!
I'm using anchors together with custom dialogs and custom dropdowns.
Is there a way to exclude some anchors from being targeted from zenscroll?

Thanks

**Comment by zengabor** [comment]
Does the reply for #37 answer your question?

**Comment by MartinMuzatko** [comment]
Thanks for the quick answer @zengabor. Unfortunately no. I'm using zenscroll in a project based on Atlassian UI: https://docs.atlassian.com/aui/latest/docs/dropdown2.html
Which relies on using anchors for targeting dropdowns/dialogs. So _custom_ is not entirely true. I don't have control over these.

**Comment by zengabor** [comment]
So you don't have control over the JavaScript but have control on the HTML? You want to mark up the anchor tag, something like `<a href="..." data-zenscroll="disable"...`?

**Comment by zengabor** [comment]
You can add the `noZensmooth` class to those anchors you want to exclude.
