### ISSUE TITLE
Change Navigation Active Class on Page Scroll.

### ISSUE THREAD

**Issue by gmerabishvili** [zengabor/zenscroll#44]
Hello, I have  fixed header and want to add an active class on href when I scroll to the target Id section. Can you help me?
Thank you.

**Comment by zengabor** [comment]
Wrote another little library exactly for that purpose earlier but I never publish it. So I just put it here for you: https://gist.github.com/zengabor/aa87f9c1e37176c7b9480ca35f7fb940

You can use it like this:

    Zenspot.watch(myContentDiv1, changeActiveClass1)

So if you scroll and `contentDiv1` becomes visible then your function `changeActiveClass1` is invoked.

You can also define what should happen if you scrolled to the top or to the bottom, e.g.,

    Zenspot.onTop(resetNavigationStyles)
    Zenspot.onBottom(doSomething)
