### ISSUE TITLE
Issue scrolling on Safari

### ISSUE THREAD

**Issue by dawaltconley** [zengabor/zenscroll#45]
I'm having an issue where a custom scroller (created by `zenscroll.createScroller`) fails to scroll in Safari (v10.1.1). The normal `zenscroll.to(etc)` functions work, but the custom scroller fails, no matter what element I give it as the scrollable element. This includes the documentElement, which is what I assume the basic functions are using, and which works in Chrome/Firefox with a custom scroller.

May be pretty specific (the scrollable div example in https://zengabor.github.io/zenscroll/ seems to work fine in Safari), so I'll include more details as I look into it out but right now I'm pretty stumped.

**Comment by zengabor** [comment]
Could you fix the issue?

**Comment by dawaltconley** [comment]
Just looked into this again. At least now, Safari(v10.1.2) scrolls when the custom scroller takes the document body as the scrollable element, but not the documentElement. Meanwhile, Chrome (63.0.3239.132) and Firefox (58.0.1) only scroll the documentElement, and _not_ the document body.

I tested this on one of my sites with nothing fancy in the way of scrollable divs-within-divs. Also tested at https://zengabor.github.io/zenscroll/ using a custom scroller created in the console. On all browsers, the scrollable div example still works; so it may be that the problem is not with the custom scroller, but with browser inconsistency, Safari being the odd one out.
