### ISSUE TITLE
Importing Zenscroll in a React project brings down my entire application

### ISSUE THREAD

**Issue by shockey** [zengabor/zenscroll#50]
```
Environment:

Safari 11.0 + Chrome 63.0.3239.84
macOS 10.13
zenscroll@4.0.0 via npm
react@15.3.2 via npm
```

I'm trying to use Zenscroll in a React project (http://ppf.audio), but upon importing the module like so:

```js
import zenscroll from 'zenscroll'
```

I get a particularly nasty error that breaks my application:

```js
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at isNativeSmoothScrollEnabledOn (zenscroll.js:66)
    at zenscroll.js:262
    at zenscroll.js:47
    at zenscroll.js:59
    at zenscroll.js:357
    at initModule (vendor.js:42)
    at require (vendor.js:59)
    at expanded (vendor.js:34)
    at index.js:15
    at initModule (vendor.js:42)
```

I'm not doing anything with the `zenscroll` reference - just importing it.

**Comment by shockey** [comment]
Update: this is happening to `swagger-ui` users as well, see referenced issue above. The underlying issue appears to be that running a bundle that includes a reference to Zenscroll before `document.body `is available (i.e., a synchronous `<script>` tag in the document head) blows everything up.

**Comment by zengabor** [comment]
Thank you for reporting, it's a shame. I will look into that.

**Comment by meydominic** [comment]
Any updates on this issue?

**Comment by zengabor** [comment]
Version 4.0.1 is released with the fix. Sorry about this bug!

**Comment by shockey** [comment]
Thanks, @zengabor & @leocaseiro!
