### ISSUE TITLE
Importing zenscroll causes Next.js app's back button to error

### ISSUE THREAD

**Issue by dargue3** [zengabor/zenscroll#52]
Was importing zenscroll into the `<App>` component of my server-rendered (`nextjs v4.2.2`) app. Whenever I would hit the back button I would get a cryptic error that blocked the back button functionality:

`Uncaught (in promise) TypeError: Parameter 'url' must be a string, not undefined`

The only further information I can provide is that hitting the back button leading you back to the page **that the server rendered** works fine, but hitting the back button leading towards any other page would lead to this error.

Removing the `import zenscroll from 'zenscroll'` line fixes any errors.

**Comment by pukapukan** [comment]
Came across the same issue.  It seems like the zenscroll's popstate conflicts with next.js's router.  is there a way to disable forward/back button support in zenscroll?

**Comment by pukapukan** [comment]
Should've read the doc first.  Setting window.noZensmooth=true resolves the issue.

https://github.com/zengabor/zenscroll#disabling-automatic-smoothing-on-local-links
https://github.com/zengabor/zenscroll/blob/dist/zenscroll.js#L258

**Comment by zengabor** [comment]
Thanks for investigating the issue and finding a fix!
