### ISSUE TITLE
isNativeSmoothScrollEnabledOn Issue

### ISSUE THREAD

**Issue by MartinClement** [zengabor/zenscroll#54]
Hi,

I tryed to update senscroll lib form 3.3.0 to 4.0.0 and I'm encountering an issue with the isNativeSmoothScrollEnableledOn function.

In chrome I get this error:

> Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

The difference between those two versions for this function is that the 4.0.0 one is not containing the condition "elem !== null" anymore.

v4.0.0
`	var isNativeSmoothScrollEnabledOn = function (elem) {
		return ("getComputedStyle" in window) &&
            window.getComputedStyle(elem)["scroll-behavior"] === "smooth"
	}`

v3.3.0
`       var isNativeSmoothScrollEnabledOn = function (elem) {
            return ("getComputedStyle" in window) && elem !== null && window.getComputedStyle(elem)["scroll-behavior"] === "smooth"
	}`

Can you tel me why the version 4.0.0 is ommiting this condition and how to make the librairy working without it ?

Have a good day,

Clement.

**Comment by zengabor** [comment]
Thank you, I am fixing this right now, and will release 4.0.1 soon

**Comment by zengabor** [comment]
Version 4.0.1 is released with the fix. Sorry about this bug!
