### ISSUE TITLE
Scroll to <a name="anchor"></a> doesn't get smooth

### ISSUE THREAD

**Issue by Finesse** [zengabor/zenscroll#55]
Hello! Zenscroll is the best anchor scroll library I've found, I really like it.

But it has a disadvantage: when you click a link pointing to an element like `<a name="about"></a>` the scroll doesn't get smoothed. Demo: https://codepen.io/TheFinesse/pen/QQYqQB.

#### Suggested solution

Change [the line 328](https://github.com/zengabor/zenscroll/blob/dist/zenscroll.js#L328) from

```js
var targetElem = document.getElementById(href.substring(1))
```
to
```js
var anchor = href.substring(1);
var targetElem = document.getElementById(anchor)
if (!targetElem) {
    var elements = document.getElementsByName(anchor)
    for (var i = 0; i < elements.length; ++i) {
        if (elements[i].tagName === 'A') {
            targetElem = elements[i]
            break
        }
    }
}
```
or to (not fully correct)
```js
var anchor = href.substring(1);
var targetElem = document.getElementById(anchor) || document.getElementsByName(anchor)[0]
```

**Comment by zengabor** [comment]
Thank you very much. I have included your change in this beta version: https://gist.github.com/zengabor/a1aad539e1567d6e9c1168d11380c5fa
