### ISSUE TITLE
Scroll animation hits page bottom

### ISSUE THREAD

**Issue by Finesse** [zengabor/zenscroll#56]
Imagine there is a page 2000px height. The screen height is 900px. The target block top Y position is 1700px.

If you are at the top of this page and click a link pointing to the block, an smooth starts. The scroll goes smoothly and stops sharply hitting the bottom of the page.

It happens because the page has the maximum scroll Y equals 1100px (page height - screen height) while Zenscroll tries to scroll to 1700px.

![2](https://user-images.githubusercontent.com/9006227/36829520-3e70f8ae-1d6b-11e8-9a22-9442b818f4d2.png)

**Comment by zengabor** [comment]
Thanks a lot. It has been fixed in [`v5`](https://github.com/zengabor/zenscroll/blob/dist/zenscroll5.js)
