### ISSUE TITLE
Scroll up from the bottom of the page doesn't work

### ISSUE THREAD

**Issue by Finesse** [zengabor/zenscroll#57]
How to reproduce:

1. Make a page with a horizontal scroll bar at the bottom.
2. Scroll manually to the very bottom of the page.
3. Try to scroll up using Zenscroll: `zenscroll.toY(0)`.

Zenscroll will scroll a bit and stop. This expression become equals `false` and makes it stop:

```js
p < 1 && (container.getHeight() + y) < container.body.scrollHeight
```

It is false because `container.getHeight() + y` > `container.body.scrollHeight`. It happens because `window.innerHeight` includes the height of the scroll bar while `document.scrollingElement` doesn't.

I suggest to use `document.documentElement.clientHeight` instead of `window.innerHeight` because it doesn't include the scroll bar height.

I tried it in Windows Chrome. It doesn't happen in masOS Chrome because scroll bar height is 0 in macOS.

**Comment by zengabor** [comment]
Thank you so much! Will include this fix in the next release

**Comment by zengabor** [comment]
This change is now included in this beta version: https://gist.github.com/zengabor/a1aad539e1567d6e9c1168d11380c5fa

**Comment by Finesse** [comment]
Thank you
