### ISSUE TITLE
Not working in MS Edge, IE or Safari

### ISSUE THREAD

**Issue by leereichardt** [zengabor/zenscroll#59]
When trying to scroll to an element, I'm getting an error of scrollHeight is undefined on the object.

This is the problematic line

`if (p < 1 && (container.getHeight() + y) < container.body.scrollHeight) {`

when I console out container on Chrome, I get the expected result (HTML tag). When I console it out on the other browsers, I basically get the result of this

```
{
  setup: setup,
  to: scrollToElem,
  toY: scrollToY,
  intoView: scrollIntoView,
  center: scrollToCenterOf,
  stop: stopScroll,
  moving: function () { return !!scrollTimeoutId },
  getY: container.getY,
  getTopOf: container.getTopOf
}
```

Any ideas?

**Comment by leereichardt** [comment]
My JS is built with Webpack. Not sure if this is an issue

**Comment by zengabor** [comment]
Thank you, I will try to reproduce this

**Comment by leereichardt** [comment]
Have you been able to replicate this? I see the example page is working fine in these browsers so I'm not sure what the difference is?

**Comment by zengabor** [comment]
No, I could not reproduce it. Is there a public page where I can see the issue?

**Comment by Arlodotexe** [comment]
I'm also getting this issue in Edge and am also building with Webpack. I really want to use Zenscroll but if it doesn't work in all major browsers then I can't....

**Comment by Arlodotexe** [comment]
It works in Edge if you don't bundle it with webpack

**Comment by zengabor** [comment]
I wish I could work on this but I am very busy with other stuff now.

Any chance you could investigate and help me fix it?

**Comment by Arlodotexe** [comment]
Unfortunately not right now, I have far too many active projects going

**Comment by joe-askattest** [comment]
Fyi for anyone else encountering this; I hit what looked like this exact bug. It turned out it was because I had to make a scroller for it it to work in Edge and Safari. i.e. `zenscroll.createScroller( area ).to( target )`

If you have the smooth scrolling setup then it works In Firefox and Chrome *without* a scroller. As a result it looks like it works in some browsers, but not others.
