### ISSUE TITLE
Does not work in an iframe, only on iOS

### ISSUE THREAD

**Issue by apod42** [zengabor/zenscroll#6]
Hello,
1. Start with two html files, main.html and iframe.html.
2. Add the script to iframe.html (this file should contain some anchor links, to test the navigation).
3. From main.html call iframe.html in an iframe: <iframe src="iframe.html" style="width:50%;height:50%;"/>

The script does not work in this case. When the user clicks on an anchor link nothing happens (not even the jump to the selected id, without the smooth scroll effect).

This happens only on devices running iOS (tested on an iPad 3 and iPhone 4). On Android and virtually all browsers on windows everything works just fine.

Another important point. Tested other smooth scroll scripts, with the same results (work on everything eles except iOS). The problem is not with your script but some sort of iOs bug.

Maybe you can come up with a fix. I don't own a Mac so I can not debug this. I have no way of opening a javascript console on iOS devices.

Thank you for a great script!

**Comment by zengabor** [comment]
@apod42 could you share the code on jsfiddle or somewhere so I can take a look?

**Comment by apod42** [comment]
Thank you! For a working example please see here: http://www.nightskyinfo.com/iframe/

Source code of the main html file: http://www.nightskyinfo.com/iframe/index.txt

Souce code of the html file beeing iframed here: http://www.nightskyinfo.com/iframe/iframe.txt

**Comment by apod42** [comment]
Notice that the iframe is wrapped in a div to make iOS diplay it like an iframe..

**Comment by zengabor** [comment]
Thank you. I can reproduce the issue. I will look into this.

**Comment by zengabor** [comment]
Unfortunately I don't have access to your code anymore. However, I just released version 3.2.1 which changes the way containers are handled. Could you give it a try?
