### ISSUE TITLE
Allow disabling of default anchor scrolling

### ISSUE THREAD

**Issue by AlecRust** [zengabor/zenscroll#61]
I have some links with `href="#"` in my app, and been reading through https://github.com/zengabor/zenscroll/issues/13 and https://github.com/zengabor/zenscroll/issues/37 since I have the same issue. I want to call Zenscroll programmatically without this default behaviour.

It feels like the [Disabling automatic smoothing on local links](https://github.com/zengabor/zenscroll#disabling-automatic-smoothing-on-local-links) docs are a misleading, since `window.noZensmooth = true` doesn't actually disable the behaviour if you have `href="#"` links ( which are quite common).

I can't change all the `href` values in my app, and currently have no way to disable this functionality. Adding an option to `zenscroll.setup()` to fully disable this might be a solution?

**Comment by zengabor** [comment]
`window.noZensmooth = true` should work if it’s set before the script is loaded. 

However, you can also add a class to the individual links to exclude them:

    <a href="#about" class="noZensmooth">

This is described in [1.6](https://github.com/zengabor/zenscroll#16-exclude-a-link-from-the-automatic-smooth-scrolling)

**Comment by AlecRust** [comment]
`window.noZensmooth = true` doesn’t work for me, I’m `require`ing Zenscroll and wherever I try to disable it within my app doesn’t work.

Seems the disabling only works in the simpler case where you can control load order? Shouldn’t setting that property always work even if it’s set later?

**Comment by zengabor** [comment]
Yes, you are probably right. I should change this.

**Comment by zengabor** [comment]
Here's a variant where this has been fixed: https://gist.github.com/zengabor/a1aad539e1567d6e9c1168d11380c5fa
