### ISSUE TITLE
Please issue an Open Source licence

### ISSUE THREAD

**Issue by mirabilos** [zengabor/zenscroll#65]
The “Unlicense” is not a licence but a Public Domain dedication. These are not valid in many countries, e.g. most of the EU except the UK.

Please assign a copyright licence as fallback in those jurisdictions in which your Public Domain dedication is not acceptable, ideally something like [MIT](https://opensource.org/licenses/mit-license.php) or [MirOS](http://www.mirbsd.org/MirOS-Licence.htm), or publish zenscroll under [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) which basically _is_ PD dedication plus fallback licence (on the right to issue a licence, not on the work itself, so kinda a meta licence).

**Comment by mirabilos** [comment]
Incidentally, https://github.com/zengabor/zenscroll/blob/e71b5c9a95ebb015001397d19deefcba01a2c0f4/zenscroll.js#L5-L7 is contradictory: Public Domain literally means absence of copyright protection, so, by the © statement, this might not match what you were intending.

Using a proper OSS licence, on the other hand, grants others the rights needed in most, if not all, jurisdictions.

**Comment by zengabor** [comment]
Thanks for your comments, I will look into this

**Comment by zengabor** [comment]
[`v5`](https://github.com/zengabor/zenscroll/blob/zengabor-v5-0-0/zenscroll5.js) has Apache License, Version 2.0
