### ISSUE TITLE
OnDone function of 'toY' triggers before last scroll

### ISSUE THREAD

**Issue by OmegaRidleyy** [zengabor/zenscroll#70]
i've got a list of divs. On the scroll event of the container div i check if i stopped scrolling with setTimeout and clearTimeout. When stopped, i center one of the divs with 'toY' and in the OnDone function i call the clearTimeout once more. But somehow for some reason the scroll event of the container div still gets called once more at the end. but only once and i can't find out why.

```
$(".search-results-container").on("scroll", function () {
    console.log("start scroll")

    if (timer !== null) {
        clearTimeout(timer);
    }

    timer = setTimeout(function () {
        console.log("stopped scrolling")

        var myScroller = zenscroll.createScroller($(".search-results-container")[0])
        var mostVisible = getMostVisible($(".user-list-result"))

        console.log("scroller scrolls")
        myScroller.toY(mostVisible[0].offsetTop - 50, 100, () => {
            console.log("clear timer")
            clearTimeout(timer)
        }
    }, 500);
})
```

console:
16'start scroll'
'stopped scrolling'
'scroller scrolls'
6'start scroll'
'clear timer'
'start scroll'       <------ why does this happen?
'stopped scrolling'
'scroller scrolls'
'clear timer'

**Comment by zengabor** [comment]
Would you mind trying it with promises? Here's a version with promises: https://gist.github.com/zengabor/a1aad539e1567d6e9c1168d11380c5fa

**Comment by zengabor** [comment]
And here's [`v5`](https://github.com/zengabor/zenscroll/blob/zengabor-v5-0-0/zenscroll5.js) with Promise
