### ISSUE TITLE
How to use in Next.js

### ISSUE THREAD

**Issue by a4vg** [zengabor/zenscroll#73]
I'm trying to include zenscroll in a Next.js project adding `import zenscroll from "zenscroll"` in a component. It works fine until I call some function and it crashes with a `TypeError: zenscroll__WEBPACK_IMPORTED_MODULE_4___default.a.setup is not a function` error.

My code looks like this

```js
import zenscroll from "zenscroll";

const Header = () => {
  zenscroll.setup(null, 42); // crashes
  return (
       ...
   )
```

I tried
```js
console.log(zenscroll); // {setup: ƒ, to: ƒ, toY: ƒ, intoView: ƒ, center: ƒ, …}
console.log(zenscroll.setup)
/*
ƒ (newDefaultDuration, newEdgeOffset) {
			if (newDefaultDuration === 0 || newDefaultDuration) {
				defaultDuration = newDefaultDuration
			}
			if (newEdgeOffset === 0 || newEdgeOffset) {
				edgeOff…
*/
```
it's clearly a function, but it doesn't work.

Am I not using zenscroll correctly? or this is completely unrelated and it has to do with something else in my project?

**Comment by shelleyphant** [comment]
I'm using Gatsby, but they're both react-based, so I would guess implementation is the same. Instead of using **import**, I used **require**

``` javascript
var zenscroll = require('zenscroll');
zenscroll.setup(null, 80);
```

**Comment by zengabor** [comment]
Hello @a4vg, this would work now with [`v5`](https://github.com/zengabor/zenscroll/blob/zengabor-v5-0-0/zenscroll5.js)
